version: '3.8'

services:
  fastapi:
    build:
      context: ./
    command: >-
      bash -c "uvicorn main_fastapi:app --host 0.0.0.0 --reload --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
      - "./alembic:/code/alembic"
      - "./alembic.ini:/code/alembic.ini"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: