version: '3.8'

services:
  fastapi:
    build:
      context: ./
    command: >-
      bash -c "uvicorn main_fastapi:app --host 0.0.0.0 --reload --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
      - "./alembic:/code/alembic"
      - "./alembic.ini:/code/alembic.ini"
    depends_on:
      - postgres
      - s3
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3:
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DOMAIN=s3.local
    image: minio/minio:RELEASE.2023-05-27T05-56-19Z
    command: ["server", "--console-address", ":9001", "--address", "0.0.0.0:9002", "/data"]
    ports:
      - '9001:9001'
      - '9002:9002'
    networks:
      default:
        aliases:
          - s3.local
    volumes:
      - minio-data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      echo 'Setting up MinIO alias';
      /usr/bin/mc alias set myminio http://s3.local:9002 minio minio123;
      echo 'Creating bucket meals if it does not exist';
      /usr/bin/mc mb --ignore-existing myminio/meals;
      echo 'Setting bucket policy to public';
      /usr/bin/mc anonymous set public myminio/meals;
      echo 'Bucket setup complete';
      "

networks:
  default:
    name: my_network

volumes:
  pgdata:
  minio-data: