"""remove price

Revision ID: 17a8da7bd990
Revises: 513f2b979db2
Create Date: 2024-01-20 10:33:35.651366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a8da7bd990'
down_revision: Union[str, None] = '513f2b979db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
