"""Added initial table

Revision ID: 4c1a06701709
Revises: 618616b7cdef
Create Date: 2024-01-17 19:05:31.343046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1a06701709'
down_revision: Union[str, None] = '618616b7cdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_category_association')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_category_association',
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='meal_category_association_category_id_fkey'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], name='meal_category_association_meal_id_fkey'),
    sa.PrimaryKeyConstraint('meal_id', 'category_id', name='meal_category_association_pkey')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    # ### end Alembic commands ###
