"""

Revision ID: 8572df601bfb
Revises: 44ba0a4364d1
Create Date: 2024-12-11 11:53:59.468070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8572df601bfb'
down_revision: Union[str, None] = '44ba0a4364d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'user', ['user_email'], ['email'])
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'user', ['user_id'], ['id'])
    op.drop_column('refresh_tokens', 'user_email')
    # ### end Alembic commands ###
