"""initial_migration

Revision ID: 9c42847fd8f4
Revises: a71a5006de9e
Create Date: 2023-11-25 09:37:25.940607

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c42847fd8f4"
down_revision: Union[str, None] = "a71a5006de9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meals_description"), "meals", ["description"], unique=False)
    op.create_index(op.f("ix_meals_id"), "meals", ["id"], unique=False)
    op.create_index(op.f("ix_meals_name"), "meals", ["name"], unique=False)
    op.create_index(op.f("ix_meals_price"), "meals", ["price"], unique=False)
    op.create_index(op.f("ix_meals_user_id"), "meals", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meals_user_id"), table_name="meals")
    op.drop_index(op.f("ix_meals_price"), table_name="meals")
    op.drop_index(op.f("ix_meals_name"), table_name="meals")
    op.drop_index(op.f("ix_meals_id"), table_name="meals")
    op.drop_index(op.f("ix_meals_description"), table_name="meals")
    op.drop_table("meals")
    # ### end Alembic commands ###
