"""add datetime

Revision ID: d715edd90ccf
Revises: 675b3c2aa2bc
Create Date: 2024-07-07 09:32:09.996698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'd715edd90ccf'
down_revision: Union[str, None] = '675b3c2aa2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute(text("UPDATE comment SET created_at = NOW() WHERE created_at IS NULL"))
    op.alter_column('comment', 'created_at', nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
